name: lint

on: push

jobs:
  # TODO: add license check
  lint-cxx:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Run Clang-format
        uses: DoozyX/clang-format-lint-action@v0.14
        with:
          extensions: "c,h,cpp"
          clangFormatVersion: 14
          style: "{IndentWidth: 4, ColumnLimit: 120, AlignEscapedNewlines: DontAlign}"
